package com.example.student_registration;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import javax.sql.DataSource;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

@Repository
public class StudentRepository {

    private final DataSource dataSource;

    @Autowired
    public StudentRepository(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    // 1. CREATE (Raw JDBC Insert)
    public Student save(Student student) {
        String sql = "INSERT INTO students (first_name, last_name, email, enrollment_date) VALUES (?, ?, ?, ?)";

        try (Connection conn = dataSource.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, student.getFirstName());
            stmt.setString(2, student.getLastName());
            stmt.setString(3, student.getEmail());
            stmt.setDate(4, Date.valueOf(student.getEnrollmentDate()));

            stmt.executeUpdate();

            // Fetch the auto-incremented ID generated by MySQL
            try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    student.setStudentId(generatedKeys.getInt(1));
                }
            }
            return student;
        } catch (SQLException e) {
            throw new RuntimeException("Database error during student registration: " + e.getMessage(), e);
        }
    }

    // 2. READ ALL (Raw JDBC Select)
    public List<Student> findAll() {
        String sql = "SELECT * FROM students";
        List<Student> students = new ArrayList<>();

        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                Student student = new Student();
                student.setStudentId(rs.getInt("student_id"));
                student.setFirstName(rs.getString("first_name"));
                student.setLastName(rs.getString("last_name"));
                student.setEmail(rs.getString("email"));
                student.setEnrollmentDate(rs.getDate("enrollment_date").toLocalDate());
                students.add(student);
            }
            return students;
        } catch (SQLException e) {
            throw new RuntimeException("Database error while fetching records: " + e.getMessage(), e);
        }
    }

    // 3. UPDATE (Raw JDBC Update)
    public Student update(Student student) {
        String sql = "UPDATE students SET first_name = ?, last_name = ?, email = ? WHERE student_id = ?";

        try (Connection conn = dataSource.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, student.getFirstName());
            stmt.setString(2, student.getLastName());
            stmt.setString(3, student.getEmail());
            stmt.setInt(4, student.getStudentId());

            int rowsUpdated = stmt.executeUpdate();
            if (rowsUpdated == 0) {
                throw new RuntimeException("Update failed: Student profile not found with ID " + student.getStudentId());
            }
            return student;
        } catch (SQLException e) {
            throw new RuntimeException("Database error during update operation: " + e.getMessage(), e);
        }
    }

    // 4. DELETE (Raw JDBC Delete)
    public void deleteById(Integer studentId) {
        String sql = "DELETE FROM students WHERE student_id = ?";

        try (Connection conn = dataSource.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, studentId);
            stmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Database error during deletion operation: " + e.getMessage(), e);
        }
    }
}